# fly.toml app configuration file generated for geekly-media-shop-client on 2024-01-09T09:04:28-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "geekly-media-shop-client"
primary_region = "bog"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
