# fly.toml app configuration file generated for geekly-media-shop-server on 2024-01-09T13:11:58-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "geekly-media-shop-server"
primary_region = "bog"

[build]

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"
  initial_size = "1gb"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
